Added Coins list on landing page with chart
Smerly/crypto-simulator pull request #6
Opened 2023-10-19 02:23 UTC by Smerly

Added Coins list on landing page with chart

2023-10-19 17:20 UTC, yoloOnTheBattlefield requested changes

2023-10-19 17:20 UTC, yoloOnTheBattlefield commented on src/Components/CoinListComponent/EachCoin.js
> +    }
these mini functions should be in a separate file called utils

2023-10-19 17:20 UTC, yoloOnTheBattlefield commented on src/Components/CoinListComponent/EachCoin.js
> +    })
you can use map for this instead of for Each

2023-10-20 18:53 UTC, mallharpreet approved these changes

2023-10-20 18:53 UTC, mallharpreet commented on src/Components/CoinListComponent/CoinList.js
> +        setRenderedCoin(renderedCoin.sort((a, b) => {
[...renderedCoin].sort.....

2023-10-20 18:53 UTC, mallharpreet commented on src/Components/CoinListComponent/CoinList.js
> +        setRenderedCoin(renderedCoin.sort((a, b) => {
sort is mutating the array

2023-10-22 01:42 UTC, merged